### ISSUE TITLE
Not working with VS 2019 16.7.2

### ISSUE THREAD

**Issue by emmalexandria** [hicknhack-software/semantic-colorizer#34] opened 2020-08-23 16:38 UTC
I downloaded this to try and emulate a VSCode theme that I like a lot, unfortunately the highlighting does not work. I also tried it on Visual Studio 16.5 prior to 16.7 and had no luck there either.

**Comment by wkoeter** [comment] 2020-12-04 08:36
I got it to work by setting the Editor Color Scheme back to Visual Studio 2017. By having it on Visual Studio 2019 it overrides all the SemanticColorizer picks.

Tools > Options > Text Editor > C# > Advanced > Editor Color Scheme

edit: See now its a possible duplicate of #33

**Closed as completed** 2020-12-06 00:19 UTC
Labels: bug, duplicate
